language: python
sudo: false
dist: trusty

python:
    - '2.7'
    - '3.5'
    - '3.6'

before_install:
    # - TRAVIS_PYTHON_VERSION=`python --version |& awk '{print $2}'|awk -F'.' '{print $1"."$2}'`
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget http://repo.continuum.io/miniconda/Miniconda3-latext-Linux-x86_64.sh -O miniconda.sh;
      fi    
    - echo $TRAVIS_PYTHON_VERSION
    # - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p ${HOME}/.miniconda
    - export PATH=${HOME}/.miniconda/bin:${PATH}
    - export C_INCLUDE_PATH=${HOME}/.miniconda/include:${C_INCLUDE_PATH}
    - export LD_LIBRARY_PATH=${HOME}/.miniconda/lib:${LD_LIBRARY_PATH}
    - conda update --yes conda

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy h5py pyyaml matplotlib openblas
    - conda install --yes -c atztogo phonopy
    - pwd
    - ./get_nanoversion.sh
    - cat __nanoversion__.txt
    - python setup.py install

script:
    - cd test/phono3py
    - python -m unittest discover -b
    - cd ../..
    - cd example/Si-PBE
    - tar xf vasprun_xmls.tar.lzma --lzma
    - phono3py --cf3 vasprun_xmls/disp-{00001..00111}/vasprun.xml
    - cd ../..
    - cd example/Si-pwscf
    - tar xf supercell_out.tar.lzma --lzma
    - phono3py --pwscf --cf3 supercell_out/disp-{00001..00111}/Si.out
    - cd ../..

deploy:
    # testing pypi
    - provider: pypi
      server: https://testpypi.python.org/pypi
      skip_cleanup: true
      distributions: sdist
      user: atztogo
      password:
        secure: "NiGCFUvUZALME/raOyq5AspTc0sCBA+G7frAIAWLsNOk7JL25UIu/T4ufWHEpvssvXZ/zntEVKEnQo8kQYQfsfDtLccdVFKJ6jzKtqbL4s2+m8d61b+Ezu9mK1XM/ImiIkvhCD+j8jtzUbN24/qYhGgR8YeXxwfCJWU7SKNueTiyBT+xOoO4gswoRpA4Ztutzows0rKX1K/MBaKF9RGotIHCIay4ryWJUg9KWcp2rKGJeDiuTK81kSyZA1MV3x05PgnPH+gxTy8XbBP0Bk71FZUpkpQ7+UsmsUSLB9dlSgkhziYuDHb4Y48YO2XqHU7bi+pElUs660eez8m8IC5dUhjY3RPDQOSb3gpc1N56/RqfMugUyelEqfXaSCPBrXfhsvutwibA4ITNh4f86jylWFUQukHiK95NCVrvMDkNcFyNZVNHsWUIBWfCXPu4fmykOb4PR1eC1kZsuo0h3VTSzMn7vtFXbedt3VtaZMNEdbBMgKxoPwcE2DPBzZDZdSbVA8QuvmbwjGpxHNISssNzLhCVWbXSbjo2BntHzMIodz36rKQwqHqw58yUBNRZKLT1/0D2qGSSWQ/r4W6w2y7XoJXyJOIGRaAzTEWmGMZ7OHO1XON9cT8zOmikC9XhmC34mhzRrKmPx/5VMyzvM05wkCpNynx0SZc6w9wmIxhFl3Q="
      on:
        repo: atztogo/phono3py
        branch: rc
        tags: false
        # python: 2.7

    # testing anaconda
    - provider: script
      skip_cleanup: true
      script: conda/anaconda_deploy.sh rc $ANACONDA_TOKEN $TRAVIS_BRANCH
      on:
        repo: atztogo/phono3py
        branch: rc
        tags: false
        # python: 2.7

    # production pypi
    - provider: pypi
      skip_cleanup: true
      distributions: sdist
      user: atztogo
      password:
        secure: "lqT3bcoiVePhx642M/dZBsnd8WUsYush58IGB2EiCu60FOhwfFJtSNEoJoKicGy54QiQ/Ho6xTcshf398CFSE2cVfW+YrTUtUaObOzFNLbmbvy5tnuvDgK/56T5jTCAVQaD68qDNR0O5qlnw/Xe8ZKoKTpoFwfnIv3brpokUFyMFcECuCtv2sNrVSF3d89S7jd9ahpjkvu0udA4jXKdwLMbjOmrpK7v7jkCtNXdJFLzprB4Y8tNX08TMovWzmrHk8YOx6v2YgNxW4/bqJbe+oGofpj9RcXfYdiXY797nz7D9b7BcRi1NMWoiMqOzpnlPEccQqhqOOxddkajiXHCyJPYJ9zWj3xuC2D50KdtGb5tm+qDI3EqzIiQv0akXE3nvMPinOQkjlUN/1/HmS5s99YMSg9GvmL4bPnu3phBjoND23IMPED4rra9IToeozPHaQGRoBvLNGAl28aAzuIP0JHmHQ26BNmOvOa+CQs1SbMytv570FMi6pN/vMgaMT71uXJWsIDb9aDG6V1snsTLIbwM/TYTLFM+2OGBN86nlmWQs0V46K2kPHcUbEv8GD148j1DTS4H0wDmc8pJSHqeSI2h35pbVbZJa6bk68V3Bhre/xo+zjxwJIkOATELbQCeFXIA059+hF+tsoQ0Jnd6RrbzP3tISdVThs3u7oSoddIE="
      on:
        branch: master
        tags: false
        # python: 2.7  

    # production anaconda
    - provider: script
      skip_cleanup: true
      script: conda/anaconda_deploy.sh main $ANACONDA_TOKEN $TRAVIS_BRANCH
      on:
        repo: atztogo/phono3py
        branch: master
        tags: false
        # python: 2.7
