package:
  name: phono3py

source:
  git_url: https://github.com/atztogo/phono3py.git
  git_branch: {{ environ.get('GIT_BRANCH','master') }}

build:
  script_env:
    - GIT_BRANCH

  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - elastic = elastic:main
    #
    # Would create an entry point called elastic that calls elastic.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - numpy
    - matplotlib
    - pyyaml
    - h5py
    # - phonopy (no way was found to set channel atztogo)

  run:
    - python
    - numpy
    - matplotlib
    - pyyaml
    - h5py
    # - phonopy (no way was found to set channel atztogo)

test:
  # Python imports
  imports:
    - anharmonic

#  commands:
#    # You can put test commands to be run here.  Use this to test that the
#    # entry points work.
#    - cd example/MgO 
#    - phonopy -f vasprun.xml-001 vasprun.xml-002
#    - phonopy -p band.conf
#    - phonopy -p --nac band.conf

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://atztogo.github.io/phono3py/
  license: BSD
  summary: 'A simulation package of phonon-phonon interaction related properties'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
